2018-11-03 11:53:31,441 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 11:53:35,648 ERROR: Exception on /login [GET] [in c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\routes.py", line 35, in login
    return render_template('login.html', title='Sign In', form=loginForm)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 4, in template
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\parser.py", line 872, in subparse
    next(self.stream)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\lexer.py", line 359, in __next__
    self.current = next(self._iter)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\lexer.py", line 562, in wrap
    for lineno, token, value in stream:
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\lexer.py", line 646, in tokeniter
    raise token(lineno, filename)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\lexer.py", line 229, in __call__
    raise self.error_class(self.message, lineno, filename)
jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag
2018-11-03 11:54:52,246 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 11:54:56,628 ERROR: Exception on /login [GET] [in c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\routes.py", line 35, in login
    return render_template('login.html', title='Sign In', form=loginForm)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\h84173\documents\install\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\templates\login.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2018-11-03 11:55:20,079 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 11:56:15,450 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 13:53:45,933 INFO: Auth startup [in .\authapp\__init__.py:35]
2018-11-03 13:53:57,932 INFO: Auth startup [in .\authapp\__init__.py:35]
2018-11-03 14:19:01,981 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 14:20:09,245 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 14:20:59,792 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 14:26:32,163 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 14:27:38,513 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 14:30:04,237 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 14:31:45,571 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 14:33:56,438 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 14:35:14,053 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 14:40:21,728 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 14:42:20,067 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 14:42:48,280 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 14:47:58,594 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 15:08:25,062 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 15:16:28,831 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 15:17:02,633 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
2018-11-03 15:18:34,661 INFO: Auth startup [in C:\Users\h84173\Documents\INSTALL\EasyPHP\data\localweb\Flask_projects\auth_project\authapp\__init__.py:35]
